[package]
name = "serde_osc_macros"
version = "0.1.0"
authors = ["Colin Wallace <wallacoloo@gmail.com>"]

[dependencies]
syn = "*"
quote = "*"
serde_osc = { version = "0.1.0", path = "../serde_osc" }

[lib]
proc-macro = true
